# Generated by Django 5.2.9 on 2025-12-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="code",
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="shorturl",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
